# Generated by Django 3.2.3 on 2021-06-20 12:00

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0003_alter_advert_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='feedback_screenshot')),
                ('views', models.IntegerField(default=0)),
                ('veryfied', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.advert')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.socialmedia')),
            ],
            options={
                'verbose_name': 'JobFeedback',
                'verbose_name_plural': 'JobFeedbacks',
            },
        ),
    ]
