# Generated by Django 3.2.3 on 2021-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_jobfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jobfeedback',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='jobfeedback',
            name='withdrawn',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
