# Generated by Django 3.2.3 on 2021-07-04 05:08

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0006_auto_20210703_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='advert_video')),
                ('remarks', models.TextField()),
                ('budget', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=3, default=0, max_digits=4, null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.client')),
            ],
            options={
                'verbose_name': 'AdvertVideo',
                'verbose_name_plural': 'AdvertVideos',
                'ordering': ['-date'],
            },
        ),
    ]
