# Generated by Django 3.2.3 on 2021-07-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20210711_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.socialmedia'),
        ),
    ]
