# Generated by Django 3.2.3 on 2021-07-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='screenshot',
        ),
    ]
