# Generated by Django 3.2.3 on 2021-07-24 21:11

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0014_submissionreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_username', models.CharField(max_length=200)),
                ('screenshot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='approval')),
                ('views', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccountApproval',
                'verbose_name_plural': 'AccountApprovals',
            },
        ),
    ]
