# Generated by Django 3.2.3 on 2021-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_accountapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
