# Generated by Django 3.2.3 on 2021-07-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_profile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('w', 'Withdrawn'), ('c', 'Cancelled')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
